#define LED0_TRIS			(TRISAbits.TRISA2)	// Ref D1
#define LED0_IO				(LATAbits.LATA2)
#define POWERON_TRIS		(TRISAbits.TRISA1)
#define POWERON		         (LATAbits.LATA1)
// MRF24WB0M I/O pins
#define WF_CS_TRIS			(TRISCbits.TRISC2)
#define WF_SDI_TRIS			(TRISCbits.TRISC4)
#define WF_SCK_TRIS			(TRISCbits.TRISC3)
#define WF_SDO_TRIS			(TRISCbits.TRISC5)
#define WF_RESET_TRIS		(TRISBbits.TRISB1)
#define WF_RESET_IO			(LATBbits.LATB1)
#define WF_INT_TRIS	    	(TRISBbits.TRISB0)
#define WF_INT_IO			(PORTBbits.RB0)
#define WF_CS_IO			(LATCbits.LATC2)
#define WF_HIBERNATE_TRIS   (TRISBbits.TRISB2)
#define	WF_HIBERNATE_IO 	(PORTBbits.RB2)
#define WF_INT_EDGE		    (INTCON2bits.INTEDG0)
#define WF_INT_IE			(INTCONbits.INT0IE)
#define WF_INT_IF			(INTCONbits.INT0IF)
#define WF_SPI_IF			(PIR1bits.SSPIF)
#define WF_SSPBUF			(SSPBUF)
#define WF_SPISTAT			(SSPSTAT)
#define WF_SPISTATbits		(SSPSTATbits)
#define WF_SPICON1			(SSPCON1)
#define WF_SPICON1bits		(SSPCON1bits)
#define WF_SPICON2			(SSPCON2)
#define WF_SPI_IE			(PIE1bits.SSPIE)
#define WF_SPI_IP			(IPR1bits.SSPIP)
